# .golangci.yml - Konfigurasi untuk golangci-lint
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nlreturn
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 2
    min-occurrences: 2
  lll:
    line-length: 120
  gosec:
    excludes:
      - G404 # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - funlen
        - gocognit
        - gocyclo
